{
  imports = [
    ./appimage.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./desktop.nix
    ./direnv.nix
    ./env.nix
    ./gaming.nix
    ./graphics.nix
    ./host.nix
    ./kernel.nix
    ./localsend.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./overlays.nix
    ./packages.nix
    ./polkit.nix
    ./power.nix
    ./syncthing.nix
    ./user.nix
    ./vm-variant.nix
    ./zram.nix
  ];
}
